### ISSUE TITLE
ordinal-barでソートがしたい

### ISSUE THREAD

**Issue by akoba** [plaidev/easy-dc-dash#100]
たとえば、接客サービスのリフトアップの数字を棒グラフで表示する際に
```
dimension="campaign_id"
reduce="d.liftup_count"
```
となっている状態で、liftup_countで降順にソートして並べたりしたいです。

**Comment by otolab** [comment]
reduceの他にorder-byを追加する

**Comment by otolab** [comment]
データ投入時のnatural orderが後段まで影響をおよぼすので、もっとも単純な対応としては、datasetをcrossfilterに渡す時に並び替える方法がある。

チャート毎に異なる並び順にするのはわりと厄介で、集計値そのものを使った動的な並び替えが更に厄介。

どこまで対応するか。
