### ISSUE TITLE
number-displayのデフォルトデザイン修正

### ISSUE THREAD

**Issue by otolab** [plaidev/easy-dc-dash#106]
* [ ] デザイン取り込み

**Comment by elcih17** [comment]
mogでやる

**Comment by otolab** [comment]
色の反転など使わなそうな機能もあること、独自の構造をもたなければならないほど特殊ではないことから、v0.4系からはベースの機能に寄せる。

サイズの縮小などは、`layout="minimum"`などとして調整。
フォントサイズもテーマでいじれるようにするかどうかのノリにする。
（個別にしていさせる程、頻繁に変える内容ではない）

v0.3系としては、最小限の修正を当てるだけにする。
このIssueはそこでクローズする。
