### ISSUE TITLE
CSVダウンロードへのフォーマット適用

### ISSUE THREAD

**Issue by kojimakazuto** [plaidev/easy-dc-dash#110]
## 内容：
[d3.js](https://github.com/d3/d3-format) のフォーマットを利用して、CSVダウンロードでも小数点の桁数等のフォーマット指定を適用させたい。

**issue元：**
https://docs.google.com/spreadsheets/d/1EEhjsBSmewwNhpOEHWejhiubtT62EckqWu4I_UHyWR4/edit#gid=0&range=44:44

**Comment by kojimakazuto** [comment]
フォーマッティングを、DL後のソフトウェアで実行してはどうかという議論。

**Comment by kojimakazuto** [comment]
@akoba 
フォーマッティングをCSVダウンロード後にソフト側で実行してはどうかとい視点が抜けていたのですが、その辺り確認したいです。

**Comment by kojimakazuto** [comment]
@otolab こちら、最終的に viewer側（excelなど）でフォーマット指定するでOK、と言うことになりました。すでに時間かけていただいていたらすみませんT_T

**Comment by otolab** [comment]
@kojimakazuto どう対応しようかなーと考えはじめてたくらいなのでダイジョブですよーｗ
