### ISSUE TITLE
Tooltip の数値表記へのフォーマット適用

### ISSUE THREAD

**Issue by kojimakazuto** [plaidev/easy-dc-dash#111]
## 内容：
グラフホバー時の Tooltip の数値表記にも [d3.js](https://github.com/d3/d3-format) のフォーマット適用させたい。

**issue元：**
https://docs.google.com/spreadsheets/d/1EEhjsBSmewwNhpOEHWejhiubtT62EckqWu4I_UHyWR4/edit#gid=0&range=34:34

![image](https://user-images.githubusercontent.com/3478945/30681675-7d56ede8-9ee1-11e7-8a03-5a78655d7492.png)

**Comment by kojimakazuto** [comment]
下記 PR で対応：
https://github.com/plaidev/easy-dc-dash/pull/117

**Comment by otolab** [comment]
tooltip周りのコードが混乱していたので整理。
PR #117 はクローズ。 #119 で対応
