### ISSUE TITLE
ヒートマップにもx-axis-label/y-axis-labelを表示したい

### ISSUE THREAD

**Issue by akoba** [plaidev/easy-dc-dash#112]
↓ここです
<img width="527" alt="clone_of_user_report_-_editing" src="https://user-images.githubusercontent.com/2390699/30689481-09aa28f4-9efc-11e7-8ce8-927839c7fe57.png">

**Comment by otolab** [comment]
現状、dc.jsでもcordinationGridとして扱われていないため、軸なしの扱いになっている。
今後変更される兆しもあるので、対応する
