### ISSUE TITLE
CSVダウンロードをShiftJISでできるようにしたい

### ISSUE THREAD

**Issue by akoba** [plaidev/easy-dc-dash#116]
「ダウンロードしたCSVファイルが文字化けするんですがー」
「CSVは何のツールで開かれていますか？」
「Excelですー」

というのがすごい頻度で発生するので、お願いしたい。

**Comment by otolab** [comment]
* [ ] iconv-liteで変換を実装
* [ ] encoding設定の導入
* [ ] csv downloadにcheckbox?のUIを追加

**Comment by otolab** [comment]
iconv-liteの組み込みが意外と厄介。
es6を頑張ってつかっちゃってるからなんだけど...

iconv-liteはcommonjsで、nodeのBufferをrequireする。
rollup-plugin-node-builtinsはbuffer-es6を利用するらしく、上手く呼べないっぽい。

**Comment by otolab** [comment]
> prevent unnecessary warn as a result of commonjs plugin
https://github.com/rollup/rollup/issues/1408

buildも通ってはいるようだ。

**Comment by otolab** [comment]
rollup-plugin-commonjsで修正をしたほうが良さそう。PR書いた。

**Comment by otolab** [comment]
```
      <csv-download-button encoding="CP932"></csv-download-button>
```

指定できる値についてはこちらを参照のこと。
https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

**Comment by otolab** [comment]
https://github.com/rollup/rollup-plugin-commonjs/blob/903a8db0ec82072e32811247265a2b44f4344567/CHANGELOG.md#824
修正がリリースされたのでアップデートする。 😄

**Comment by otolab** [comment]
@akoba v0.3.3として対応完了ました。使えますー。

```
<csv-download-button encoding="CP932"></csv-download-button>
```

**Comment by akoba** [comment]
ありがとうございます！
