### ISSUE TITLE
バーチャートとラインチャートでの2軸表現を実装する

### ISSUE THREAD

**Issue by kojimakazuto** [plaidev/easy-dc-dash#172]
SITE Report を現状のModeからライブラリに置き換える要望（アクショナブルにしたい要望）があり、表題のチャートが必要になる。

![image](https://user-images.githubusercontent.com/3478945/33923163-d818f330-e012-11e7-94dd-272bfaf688d2.png)

**Comment by otolab** [comment]
TODO:
組み合わせ系は簡単に追加できるものもあるはずだが、どういう提供の仕方をするか？
