### ISSUE TITLE
アップデートの v0.3 への追加

### ISSUE THREAD

**Issue by kojimakazuto** [plaidev/easy-dc-dash#177]
追加項目：
1. https://github.com/plaidev/easy-dc-dash/pull/169
2. https://github.com/plaidev/easy-dc-dash/pull/173
3. https://github.com/plaidev/easy-dc-dash/pull/179

**Comment by kojimakazuto** [comment]
@otolab 
https://github.com/plaidev/easy-dc-dash/pull/178 の PR を出しました。
お手隙でレビュー＆追加よろしくお願いしますmm

**Comment by otolab** [comment]
0.3.12リリースしました。
