### ISSUE TITLE
data-tableのlinkColumnで、テキストとリンク先URLを別カラムの値を使いたい

### ISSUE THREAD

**Issue by akoba** [plaidev/easy-dc-dash#32]
例

|name|url|
|---|---|
|とあるプロジェクト|https://admin.karte.io/p/hoge|

のようなテーブルで、`<a href="https://admin.karte.io/p/hoge">とあるプロジェクト</a>`にしたいです。

**Comment by otolab** [comment]
#33 で対応します。
