### ISSUE TITLE
data-tableのカラムごとにフォーマットを指定したい

### ISSUE THREAD

**Issue by akoba** [plaidev/easy-dc-dash#33]
小数点以下◯桁とか、パーセント表示とか。

modeのこういうやつです。
![2017-06-09 16 55 51](https://user-images.githubusercontent.com/2390699/26966338-97a441d6-4d34-11e7-8925-151378cfbb43.png)

**Comment by otolab** [comment]
```
EasyDC.Store.registerRepresentation('percent', (val, row) => {
  return Math.floor(val*10000) / 100 + ' %'
})
EasyDC.Store.registerRepresentation('userDetailLink', (val, row) => {
  const url = `${BASE_URL}/${row.user_id}`
  return `<a href="${url}">${row.name}</a>`
})
```

```
<data-table
  dimension='user_id'
  :columns="{link: d.user_id}"
  :representations="{link: 'userDetailLink'}"></data-table>
```

**Comment by akoba** [comment]
おお、ありがとうございます！
使ってみます。

**Comment by otolab** [comment]
まだ配信する状態にできていないので、もう少しお待ち下さい。

**Comment by akoba** [comment]
@otolab registerRepresentationで指定する関数の引数のrowに、テーブルのcolumnsで指定した項目しか入っていないようですが、これは意図した動作でしょうか？
上記のサンプルの場合、columnsにnameが定義されてないのでrow.nameは参照できないのではないかと。

**Comment by otolab** [comment]
意図した動作です。今後は未指定なら全部出すようにするかもしれません。（非表示はrepresentationsでnullを指定する）

あー、サンプルというかコンセプトとして書いたものなので、動作テストはしてないです…。すんません…。

**Comment by akoba** [comment]
> 非表示はrepresentationsでnullを指定する

おお、これできるんですね。であれば問題ありません。ありがとうございます！
