### ISSUE TITLE
unittestを作る

### ISSUE THREAD

**Issue by otolab** [plaidev/easy-dc-dash#34]
idea:
jsdom, mochaでSVGの要素数の確認を行う

最低限、グラフの要素が表示されることの確認が取れることを目指す。
データ型やreduceの処理の成否などが主なチェック項目になる想定。

見た目の崩れに関しては一旦おいておく。

**Comment by elcih17** [comment]
http://qiita.com/hypermkt/items/850bf20a8ad43c13fd05
Vud.js用テストライブラリ

**Comment by elcih17** [comment]
まだβ版だけど、公式の単体テストライブラリができたらしい
https://github.com/vuejs/vue-test-utils

**Comment by otolab** [comment]
本体component2ではavoriazを使ってた。
こちらではvue-test-utilsやってみますか。APIはより自然になってる感じ。

**Comment by elcih17** [comment]
move #162
