### ISSUE TITLE
DefaultTheme のオプション設定機能

### ISSUE THREAD

**Issue by kojimakazuto** [plaidev/easy-dc-dash#48]
## 目的：
各チャートのスタイルのカスタマイズの簡便化

## 内容：
DefaultTheme の `colors` で設定されている値に、
- [ ] chartType の指定
- [ ] オプションの指定

DefaultTheme の `layout` で設定されている値に、 
- [ ] オプションの指定

**Comment by otolab** [comment]
```
<multi-lines
  dimension="date"
  reduce="[d.value]"
  layoutDetails="{margin: {left: d.margin.left+10, right: 0}}"
></multi-lines>
```
デフォルトの設定値を`d`として読むことができ、調整後の値はデフォルトの値とマージされます。　

内部では、メソッドとして解釈されています。だいたいこんな↓感じです。
```
let setting = theme.layout;
custom = function(d) { 
  return {
    margin: {left: d.margin.left+10, right: 0}
  }
}
return assignDeep({}, setting, custom(setting))
```

**Comment by otolab** [comment]
なお、layoutオブジェクトの構成はマイナーバージョンのレベルで互換性がなくなる場合があります...。
