### ISSUE TITLE
チャートのラベルに、dimensionとは違うカラムの値を使いたい

### ISSUE THREAD

**Issue by akoba** [plaidev/easy-dc-dash#56]
例えば、dimensionがcampaign_idの場合、値のラベル（下記参照）もcampaign_idになるが、IDを見せられてもわからないのでここにはcampaign_nameを表示したい。
<img width="269" alt="2017-06-22 10 09 39" src="https://user-images.githubusercontent.com/2390699/27412901-087ac454-5733-11e7-89b5-08824c7b08f2.png">

dimensionをcampaign_nameにすればいいのでは？という対応については、nameは違うIDの要素でも重複する可能性があり、重複すると同じ値に合計されてしまうのでNG。

もうすでにあったらすいません！

**Comment by otolab** [comment]
「dimensionとは違うカラム」がdimensionの値に対して一意になるかどうかがチャート側からはわからないので、ちょっとやりづらい所です。

EasyDCの外部でID / 表示名の対応を作成し、labelsにいれて反映する想定です。
管理画面のembedded-reportコンポーネントと通信する機能を入れるか、別途作成して組み合わせる予定です。

（管理画面の一部として使うなら通信できて然るべき。という判断です）

**Comment by akoba** [comment]
なるほどです。
ただ、dimensionの値に対して一意になることが自明なカラムが指定されることを前提にして、
ANY_VALUEとかで集計した結果を出しちゃうというのが、現実的にハッピーなケースも有るのかなーと思います。
dimensionの値に対して一意じゃない場合は結果は保証しないよ、でもそんな場合はそもそもその値を指定するのが間違ってるよね、という。

**Comment by otolab** [comment]
@akoba データ投入時に、指定した2つのcolumnの対から、labelsを自動生成するコードを思いついたので、その線で対応します。

**Comment by akoba** [comment]
おお！
