### ISSUE TITLE
list-rowのdescendingとcapの組み合わせが正しく動作しない

### ISSUE THREAD

**Issue by otolab** [plaidev/easy-dc-dash#74]
capで上位が絞られ、その上でdescendingされるような振る舞いになる。
また、list-rowでのマイナスの値の振る舞いが上手くない？？

**Comment by otolab** [comment]
とりあえず、reduceで-を掛ければ回避できるが。

**Comment by elcih17** [comment]
あー、orderingオプション、list-rowだけで使ってたんですね

**Comment by elcih17** [comment]
今dashboard-01で見てる感じだと、ちゃんと動いてるように見えます

**Comment by elcih17** [comment]
ここで勘違いしてたみたいです https://github.com/plaidev/easy-dc-dash/pull/3

とりあえずbaseのorderingに統一してしまいたいですね
