### ISSUE TITLE
topojsonの参照に相対パスを使うのをやめる

### ISSUE THREAD

**Issue by elcih17** [plaidev/easy-dc-dash#83]
現状相対パスでeasy-dc-dash/libs/json/**.topojsonを参照するようにしているが
modeでbundle.browser.jsを読み込むと `https://modeanalytics.com/libs/json/japan_without_suffix.topojson` のようになりエラーが起きる

**Comment by elcih17** [comment]
jsonを用意してimport、https://github.com/topojson/topojson のgeo2topoを考えたがserverが必要なので厳しい
.topojsonを.jsonにしてrollup-plugin-jsonで読み込もうとしたがうまくいかなかった
`export default '{topojson}'` のようにしてimportするという荒技を使ったがbuildの時間がかかる

topojsonをstatic.karte.ioで配信するべき？

**Comment by otolab** [comment]
rollup-plugin-topojsonを作るのがきれいな気がしてきた。
ファイル→jsonデータの変換はライブラリで行える訳なので、あとはプラグインとして組み合わせるだけ。

**Comment by elcih17** [comment]
https://github.com/rollup/rollup/wiki/Plugins#creating-plugins

**Comment by elcih17** [comment]
- [ ] `.json` として読み込む
- [ ] そのままではbuildが終わらない (sizeが大きい？) のでsimplifyする
  - https://github.com/topojson/topojson-simplify/blob/master/README.md#toposimplify
- [ ] `toposimplify -P 0.01 -o <output_file_name> <file>`
